### ISSUE TITLE
commentaires fichiers .h

### ISSUE THREAD

**Issue by zdebugs** [Tuteurs101/CR_Fillit-14-02-19#10]
**Fichier : *.h

**Code source :**
```
CODE HERE
```
**Proposition :**
```
CODE HERE
```

**Details (optionnel) :**
metres des commentaires explicatifs  a coter des fonctions ains que le non du fichiers les contenants .

**Comment by Tuteurs101** [comment]
Plus de commentaire dans les header (cf : [https://github.com/Tuteurs101/CR_Fillit-14-02-19/issues/9](url))
