### ISSUE TITLE
Malloc inutile

### ISSUE THREAD

**Issue by nerahmou** [Tuteurs101/CR_Fillit-14-02-19#12]
**Fichier :** 
main.c
**Code source :**
```
int		*ft_reference(void)
{
	int		*ref;

	if (!(ref = (int *)malloc(sizeof(int) * 20)))
		return (0);
	ref[0] = 15;
	ref[1] = 23;
...
	return (ref);
}
```
**Proposition :**
```
int main()
{
 int ref[20];

ft_ref(ref);
}
```

**Details (optionnel) :**
Pas de malloc car taille connue

**Comment by Tuteurs101** [comment]
Une allocation statique aurait pu être possible dans ce cadre car la taille du tableau est fixe et connue d'avance. Cela évite les erreurs liés au malloc, et la retombée que cela peut généré.
