### ISSUE TITLE
Protection malloc

### ISSUE THREAD

**Issue by Toreben** [Tuteurs101/CR_Fillit-14-02-19#13]
**Fichier :** ft_do_tetri.c

**Code source :**
fonction ft_do_tetri:
```
stab = (t_tetri *)malloc(sizeof(*stab) * ((len + 1) / 21));
```
```
stab[i] = ft_do_minos(buff, len, name);
```
fonction ft_do_minos :
```
if (!(t.tetri = (char **)malloc(sizeof(char *) * 5)))
		exit(0);
```
**Proposition :**

Faire attention aux fonction qui mallc et à leur eventuel retour.
Problème d'information lorsque qu'on a un exit brutal.

**Comment by Tuteurs101** [comment]
Faire attention à l'intégralité des ses mallocs, certains n'ayant aucune protection.
Il faut anticiper ce qu'un malloc à nul peut provoquer dans le fonctionnement de son programme.

Attention au exit, il peut dissimuler de véritable leaks. Free dans tous les cas avant de quitter peut être une bonne pratique
