### ISSUE TITLE
protection malloc check_error

### ISSUE THREAD

**Issue by zdebugs** [Tuteurs101/CR_Fillit-14-02-19#15]
**Fichier : ft_check_error.c

**Code source :**
```
ch = ft_init_check();
CODE HERE
```
**Proposition :**
```
if (!(ch = ft_init_check())
{
free (buff);
ft_fail();
}
```

**Details (optionnel) :**
na pas proteger son retour de malloc de sa structure , ce qui fera plante sont programme ci elle est null.

**Comment by Tuteurs101** [comment]
Les protections de mallocs impliquent de protéger les fonctions qui appellent un malloc.
