### ISSUE TITLE
Include inutile

### ISSUE THREAD

**Issue by nerahmou** [Tuteurs101/CR_Fillit-14-02-19#16]
**Fichier :** 
ft_check_error.c
**Code source :**
```
#include "fillit.h"
#include <stdlib.h>
```
**Proposition :**
```
#include "fillit.h"
```

**Details (optionnel) :**
Le "#include <stdlib.h>" est inutile car défini dans le fillit.h

**Comment by Tuteurs101** [comment]
voir [https://github.com/Tuteurs101/CR_Fillit-14-02-19/issues/8](url)
