### ISSUE TITLE
structure

### ISSUE THREAD

**Issue by Toreben** [Tuteurs101/CR_Fillit-14-02-19#18]
**Fichier :** ft_algo.c

**Code source :**
```
t_coord *c;

c = (t_coord *)malloc(sizeof(*c));
```
**Proposition :**
```
t_coord      c;

```

**Details (optionnel) :**
pas besoin de malloc cette structures, elle n'est pas modifier dans les autres fonctions.sa evite de free et reduit le nombre de fonction.
->Envoyer l'adresse de la structure pour eviter de faire une copie

**Comment by Tuteurs101** [comment]
Eviter de faire des mallocs autant que possible quand cela n'est pas nécessaire, pour diminuer les protections et remontée d'erreurs
