### ISSUE TITLE
Plusieurs fonctions ayant la meme fonction

### ISSUE THREAD

**Issue by nerahmou** [Tuteurs101/CR_Fillit-14-02-19#19]
**Fichier :** 
ft_error.c
**Code source :**
```
void	ft_error_buff(char *buff)
{
	free(buff);
	ft_fail();
}

void	ft_error_buff_ref(char *buff, int *ref)
{
	free(buff);
	free(ref);
	ft_fail();
}

void	ft_error_buff_ch(char *buff, t_check *ch, int *ref)
{
	free(buff);
	free(ch);
	free(ref);
	ft_fail();
}
```
**Proposition :**
```
void	ft_error(char *buff, t_check *ch, int *ref)
{
	free(buff);
	free(ch);
	free(ref);
	ft_fail();
}
```

**Details (optionnel) :**
Reunir les 3 fonctions de free() dans une seule

**Comment by Tuteurs101** [comment]
Une fonction aurait pu permettre de faire tout ces free, en mettant des arguments a NULL au besoin. 

rappel : free un pointeur NULL ne pose pas de problème.
+ Mettre ses pointeurs à NULL lors des free évite les double free.
