### ISSUE TITLE
Arborescence

### ISSUE THREAD

**Issue by nerahmou** [Tuteurs101/CR_Fillit-14-02-19#2]
**Fichier :** 
Makefile

**Details (optionnel) :**
Mettre les *.c dans un dossier et les *.h dans un autre

**Comment by Tuteurs101** [comment]
Structurez d'avantage son programme et séparé les .h des .c.
Le sujet avait tout de même ses contraintes ce qui explique une tel arborescence

**Comment by Tuteurs101** [comment]
Structurez d'avantage son programme et séparé les .h des .c.
Le sujet avait tout de même ses contraintes ce qui explique une tel arborescence
