### ISSUE TITLE
leak ft_map()

### ISSUE THREAD

**Issue by zdebugs** [Tuteurs101/CR_Fillit-14-02-19#20]
**Fichier : ft_map.c

**Code source :**
```
if (!(map[i] = malloc)
   return (0)
```
**Proposition :**
```
if (!(map[i] = malloc)
{
free(map)
error();
}
```

**Details (optionnel) :**
ne free pas sont sous-tableaux si il y a eu une error de malloc.

**Comment by Tuteurs101** [comment]
Lors d'une erreur de malloc, ne pas free ce qui à été alloué précédemment peut causer des leaks.
