### ISSUE TITLE
organisation Makefile

### ISSUE THREAD

**Issue by Toreben** [Tuteurs101/CR_Fillit-14-02-19#3]
**Fichier :** Makefile

**Details:**
l'organisation des variables et des règles pas forcément logique, les declaration s'entremelent

**Comment by Tuteurs101** [comment]
Etre attentif à la logique dont on déclare ses variables, doit on declaré tout ce qui concerne les includes, puis les sources, puis les libs, ou declarer tout les noms de dossier, puis tous les fichiers de ces dossiers, puis en faire le chemin complet.

**Comment by Tuteurs101** [comment]
Etre attentif à la logique dont on déclare ses variables, doit on declaré tout ce qui concerne les includes, puis les sources, puis les libs, ou declarer tout les noms de dossier, puis tous les fichiers de ces dossiers, puis en faire le chemin complet.
