### ISSUE TITLE
Allocation statique possible

### ISSUE THREAD

**Issue by spetitcuenot** [Tuteurs101/CR_Fillit-14-02-19#4]
**Fichier : ft_read.c** 

**Code source : ft_read(int fd)**
```
if (!(buff = ft_memalloc(546)))
		return (0);
```
**Proposition :**
```
char buf[546];
```

**Details (optionnel) :**
Informations supplémentaires. (Points intéressants, notion etc.)

**Comment by Tuteurs101** [comment]
Allocation nécessaire dans ce cadre là car le pointeur est retourné dans la fonction.
