### ISSUE TITLE
MACRO -VS- ENUM

### ISSUE THREAD

**Issue by nerahmou** [Tuteurs101/CR_Fillit-14-02-19#5]
**Fichier :** 
fillit.h
**Code source :**
```
# define TOO_MUCH_C -1
# define WRG_L -2
# define WRG_C -3
# define WRG_PDL -4
# define WRG_FIG -5
# define WRG_NB_L -6

```
**Proposition :**
```
enum e_error
{
     TOO_MUCH_C = -1,
     WRG_L = -2,
     WRG_C  = -3,
     WRG_PDL = -4,
     WRG_FIG = -5,
     WRG_NB_L = -6
}
```

**Details (optionnel) :**
L'utilisation d'enumeration plutot que de macros

**Comment by Tuteurs101** [comment]
Prendre en main les enum pour améliorer la lisibilité des messages d'erreurs. Les enums pouvant être plus spécifique que les #define du preprocesseurs pour remonté une erreur.
