### ISSUE TITLE
regrouper les fonctions

### ISSUE THREAD

**Issue by zdebugs** [Tuteurs101/CR_Fillit-14-02-19#6]
**Fichier : tout les fichiers *.c

**Code source :**
```
CODE HERE
```
**Proposition :**
```
CODE HERE
```

**Details (optionnel) :**

regrouper les fonctions errors/fails dans un propres fichiers.

**Comment by Tuteurs101** [comment]
Une fonction d'erreur se retrouve en dehors du fichier (ft_fail du main.c) alors qu'un fichier est fait pour (ft_error.c)
