### ISSUE TITLE
includes

### ISSUE THREAD

**Issue by zdebugs** [Tuteurs101/CR_Fillit-14-02-19#8]
**Fichier :** 

**Details (optionnel) :**
regrouper tout les includes de tout les fichiers *.c dans un fichier .h , et mettre le fichiers .h dans un dossier includes pour plus de lisibilité.

**Comment by Tuteurs101** [comment]
Etre attentif à l'organisation de nos commandes #includes. Multiples inclusion du même header (ft_check_error.c inclus stdlib.h, déjà inclus par fillit.h).

Bonne pratique : Essayer au maximum d'inclure les header qui sont spécifique à votre fichier (un .h par .c potentiellement) et d'évite d'avoir un header qui contient tout, cela diminuera la taille de votre programme après le passage du préprocesseur.
